export type Subject = {
  subject_id: string,
  title: string,
  total_units: number,
  offered_fall: boolean,
  offered_IAP: boolean,
  offered_spring: boolean,
  offered_summer: boolean,
  public: boolean,

  level?: "U" | "G",
  is_historical?: boolean,
  source_semester?: string,
  joint_subjects?: string[],
  equivalent_subjects?: string[],
  meets_with_subjects?: string[],
  quarter_information?: string,
  not_offered_year?: string,
  instructors?: string[],
  communication_requirement?: "CI-H" | "CI-HW",
  hass_attribute?: string,
  gir_attribute?: string,
  children?: string[],
  parent?: string,
  old_id?: string,

  lecture_units: number,
  lab_units: number,
  design_units: number,
  preparation_units: number,
  is_variable_units: boolean,
  is_half_class: boolean,
  has_final: boolean,

  description?: string,
  prerequisites?: string,
  corequisites?: string,
  schedule?: string,
  url?: string,
  related_subjects?: string[],
  rating?: number,
  enrollment_number?: number,
  in_class_hours?: number,
  out_of_class_hours?: number,
};
